VehicleServiceManagement/Models/UserPermission.cs
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VehicleServiceManagement.Models
{
    public class UserPermission
    {
        public Int64 Id { get; set; }
        public Int64 UserId { get; set; }
        public Int64 Form { get; set; }
        public string FormName { get; set; }
        public bool InsertPermission { get; set; }
        public bool UpdatePermission { get; set; }
        public bool DeletePermission { get; set; }
        public bool DisplayPermission { get; set; }
        public bool PrintPermission { get; set; }

        public static List<UserPermission> permissionList { get; set; }
        public List<UserPermission> GetUserPermissions(Int64 UserId = 0)
        {
            List<UserPermission> _permissions = new List<UserPermission>();

            SqlCommand com = new SqlCommand("GetUserPermission");
            com.CommandType = CommandType.StoredProcedure;
            com.Parameters.AddWithValue("@UserId", UserId);
            DataTable dt = new DataTable();
            dt = DbConnection.Read(com);
            foreach (DataRow dr in dt.Rows)
            {
                UserPermission pr = new UserPermission();

                pr.Id = Convert.ToInt64(string.IsNullOrEmpty(Convert.ToString(dr["Id"])) ? "0" : Convert.ToString(dr["Id"]));
                pr.UserId = Convert.ToInt64(string.IsNullOrEmpty(Convert.ToString(dr["UserId"])) ? "0" : Convert.ToString(dr["UserId"]));
                pr.Form = Convert.ToInt64(string.IsNullOrEmpty(Convert.ToString(dr["Form"])) ? "0" : Convert.ToString(dr["Form"]));
                pr.FormName = Convert.ToString(dr["FormName"]);
                pr.InsertPermission = Convert.ToBoolean(string.IsNullOrEmpty(Convert.ToString(dr["InsertPermission"])) ? 0 : Convert.ToInt16(dr["InsertPermission"]));
                pr.UpdatePermission = Convert.ToBoolean(string.IsNullOrEmpty(Convert.ToString(dr["UpdatePermission"])) ? 0 : Convert.ToInt16(dr["UpdatePermission"]));
                pr.DeletePermission = Convert.ToBoolean(string.IsNullOrEmpty(Convert.ToString(dr["DeletePermission"])) ? 0 : Convert.ToInt16(dr["DeletePermission"]));
                pr.DisplayPermission = Convert.ToBoolean(string.IsNullOrEmpty(Convert.ToString(dr["DisplayPermission"])) ? 0 : Convert.ToInt16(dr["DisplayPermission"]));
                pr.PrintPermission = Convert.ToBoolean(string.IsNullOrEmpty(Convert.ToString(dr["PrintPermission"])) ? 0 : Convert.ToInt16(dr["PrintPermission"]));
                _permissions.Add(pr);
            }
            return _permissions;
        }
    }
}

VehicleServiceManagement/Controllers/ControlPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VehicleServiceManagement.Models;

namespace VehicleServiceManagement.Controllers
{
    public class ControlPanelController : Controller
    {
        public static string[] gender = new string[] { "Male", "Female", "Others" };
        public IActionResult Index()
        {
            return View();
        }
        public PartialViewResult _partialControlPanelLayout()
        {
            List<UserPermission> userP = new List<UserPermission>();
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            }
            UserPermission pn = new UserPermission();
            userP = pn.GetUserPermissions(UserId);

            return PartialView(userP);
        }
        public IActionResult UserIndex()
        {         
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "UserMaster").FirstOrDefault().DisplayPermission)
                {
                    UserSettings obj = new UserSettings();
                    UserSettingsDisplay displayList = new UserSettingsDisplay();
                    displayList.userList = obj.GetAllUsers();
                    displayList.userP = UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "UserMaster").FirstOrDefault();
                    return View(displayList);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult UserSettingsdetails(int id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "UserMaster").FirstOrDefault().DisplayPermission)
                {
                    UserSettings obj = new UserSettings();
                    UserSettings user;
                    user = obj.details(id);
                    return View(user);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult UserSettingsCreate()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "UserMaster").FirstOrDefault().InsertPermission)
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public IActionResult UserSettingsCreate(UserSettings user)
        {

            UserSettings obj = new UserSettings();
            obj.create(user);
            return RedirectToAction("UserIndex");
        }

        public IActionResult UserSettingsEdit(int id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "UserMaster").FirstOrDefault().UpdatePermission)
                {
                    UserSettings obj = new UserSettings();
                    UserSettings user;
                    user = obj.details(id);

                    return View(user);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public IActionResult UserSettingsEdit(UserSettings user)
        {

            UserSettings obj = new UserSettings();
            obj.update(user);
            return RedirectToAction("UserIndex");
        }

        public JsonResult DeleteUserSettings(int Id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "UserMaster").FirstOrDefault().DeletePermission)
                {
                    UserSettings obj = new UserSettings();
                    var result = true;
                    obj.delete(Id);
                    return Json(result);
                }
            }
            return Json(false);
        }

        public IActionResult DepartmentIndex()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "Department").FirstOrDefault().DisplayPermission)
                {
                    Department dealer = new Department();
                    DepartmentDisplay displayList = new DepartmentDisplay();
                    displayList.departmentList = dealer.GetAllDepartment();
                    displayList.userP = UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "Department").FirstOrDefault();
                    return View(displayList);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult CreateDepartment()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "Department").FirstOrDefault().InsertPermission)
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public IActionResult CreateDepartment(Department department)
        {
            Department obj = new Department();
            obj.create(department);
            return RedirectToAction("DepartmentIndex");
        }
        public IActionResult EditDepartment(int id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "Department").FirstOrDefault().UpdatePermission)
                {
                    Department obj = new Department();
                    Department dep;
                    dep = obj.details(id);
                    return View(dep);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public IActionResult EditDepartment(Department department)
        {

            Department obj = new Department();

            obj.update(department);
            return RedirectToAction("DepartmentIndex");
        }

        public JsonResult Delete(int Id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "Department").FirstOrDefault().DeletePermission)
                {
                    Department obj = new Department();
                    var result = true;
                    obj.delete(Id);
                    return Json(result);
                }
            }
            return Json(false);
        }
        public IActionResult DepartmentDeatils(int id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "Department").FirstOrDefault().DisplayPermission)
                {
                    Department obj = new Department();
                    Department dealer;
                    dealer = obj.details(id);
                    return View(dealer);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }

        public IActionResult DesignationIndex()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "Designation").FirstOrDefault().DisplayPermission)

VehicleServiceManagement/Views/ControlPanel/DepartmentDeatils.cshtml
@model VehicleServiceManagement.Models.Department
@{
    ViewData["Title"] = "DepartmentDeatils";
    Layout = "~/Views/Shared/_ControlPanelLayout.cshtml";
}

<form asp-action="DepartmentDeatils" enctype="multipart/form-data">
    <div class="content">
        <div class="row">
            <div class="col-sm-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h2 class="box-title">Dealer Branch Details</h2>
                        <div class="empl-regi">

                        </div>
                    </div>


                    <div class="box-body with-border">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="empl-regi">
                                    <div class="tab-content">
                                        <div id="bi" class="tab-pane fade in active">
                                            <div class="col-sm-6">

                                                <div class="row mb-5">
                                                    <div class="col-sm-12">
                                                        <div class="form-regi">
                                                            <ul>
                                                                <li>
                                                                    <label>Name: <lable style="color:red"></lable></label>
                                                                </li>

                                                                <li>

                                                                    <label class="form-control form-control-spl">@Model.Name</label>
                                                                </li>

                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row mb-5">
                                                    <div class="col-sm-12">
                                                        <div class="form-regi">
                                                            <ul>
                                                                <li>
                                                                    <label>Code: <lable style="color:red">*</lable></label>
                                                                </li>

                                                                <li>
                                                                    <label class="form-control form-control-spl">@Model.Code</label>
                                                                    @* @Html.LabelFor(model => model.Name)*@
                                                                </li>

                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                               
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" class="btn btn-primary btn-success" value="Back" onclick="history.back()">
                </div>

            </div>
        </div>
    </div>
</form>

VehicleServiceManagement/Views/ControlPanel/DepartmentIndex.cshtml
@model VehicleServiceManagement.Models.DepartmentDisplay
@{
    ViewData["Title"] = "DepartmentIndex";
    Layout = "~/Views/Shared/_ControlPanelLayout.cshtml";
}

<script>



    var gl_Id = 0;

    function DepartmentDelete(Id) {
        gl_Id = Id;
        $("#DeleteConfirmation").modal("show");
    }
    function ConfirmDelete() {
        var id = $("#Id").val();

        $.ajax({
            type: "POST",
            url: "/ControlPanel/Delete?Id=" + gl_Id,
            success: function (data) {
                $("#DeleteConfirmation").modal("hide");
                $("table #" + id).remove();
                location.reload(true);
            }
        })

    }

    /**/</script>
<div class="box box-primary">
    <div class="box-header with-border">
        <h2 class="box-title">Department Information</h2>
    </div>
    <div class="box-body">
        <div class="row mb-7">
            <div class="col-sm-12">
                <div class="pur-in-btn">
                    <ul>
                        @if (Model.userP.InsertPermission)
                        {
                        <li><a asp-action="CreateDepartment" asp-controller="ControlPanel">New <i class="fa fa-plus"></i></a></li>
                        }
                        @*<li><a href="">Edit <i class="fa fa-edit"></i></a></li>
                            <li><a href="">Delete <i class="fa fa-trash"></i></a></li>*@
                        <li><a asp-action="index" asp-controller="ControlPanel">Cancel <i class="fa fa-ban"></i></a></li>
                        @if (Model.userP.PrintPermission)
                        {
                        <li><a href="">Print <i class="fa fa-print"></i></a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        @*<a href="#" class="btn btn-info" onclick="AddNewCity()">Add New City</a> <br /><br />*@

        <table class="table table-striped">
            <thead>
                <tr>
                    @{
                        int sno = 0;
                    }
                    <th>SL No.</th>
                    <th>Department</th>
                    <th>Code</th>
                    
                    <th>Action</th>

                </tr>
            </thead>
            <tbody id="SetDepartmentList">
                <tr id="LoadingStatus" style="color:red"></tr>
                @foreach (var item in Model.departmentList)
                {
                    <tr id="@item.Id">

                        <td>
                            @{ sno++; }
                            @sno
                        </td>
                        <td>@item.Name</td>
                        <td>@item.Code</td>
                     

                        <td>
                            @if (Model.userP.UpdatePermission)
                            {
                            <a href='#' class="btn btn-primary btn-xs btn-marign-8x fa fa-edit" title="Edit" onclick="location.href='@Url.Action("EditDepartment", "ControlPanel", new { id = @item.Id })'"></a>
                            }
                            @if (Model.userP.DisplayPermission)
                            {
                            <a href='#' class="btn btn-success btn-xs btn-marign-8x fa fa-eye" title="View" onclick="location.href='@Url.Action("DepartmentDeatils", "ControlPanel", new { id = @item.Id })'"></a>
                            }
                            @if (Model.userP.DeletePermission)
                            {
                            <a href='#' class="btn btn-danger btn-xs btn-marign-8x fa fa-trash" title="Delete" onclick="DepartmentDelete(@item.Id)"></a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="MyModal1">
</div>


<div class="modal fade" id="DeleteConfirmation">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h4 id="ModalTitle"></h4>
            </div>
            <div class="modal-body">
                <h4>Are you sure? You want to delete this record.</h4>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
            </div>
        </div>
    </div>
</div>

VehicleServiceManagement/Views/ControlPanel/DesignationIndex.cshtml
@model VehicleServiceManagement.Models.DesignationDisplay
    @{
        ViewData["Title"] = "DesignationIndex";
        Layout = "~/Views/Shared/_ControlPanelLayout.cshtml";
    }

    <script>



    var gl_Id = 0;

    function DesignationDelete(Id) {
        gl_Id = Id;
        $("#DeleteConfirmation").modal("show");
    }
    function ConfirmDelete() {
        var id = $("#Id").val();

        $.ajax({
            type: "POST",
            url: "/ControlPanel/DesignationDelete?Id=" + gl_Id,
            success: function (data) {
                $("#DeleteConfirmation").modal("hide");
                $("table #" + id).remove();
                location.reload(true);
            }
        })

    }

    /**/</script>
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Designation Information</h2>
        </div>
        <div class="box-body">
            <div class="row mb-7">
                <div class="col-sm-12">
                    <div class="pur-in-btn">
                        <ul>
                            @if (Model.userP.InsertPermission)
                            {
                            <li><a asp-action="CreateDesignation" asp-controller="ControlPanel">New <i class="fa fa-plus"></i></a></li>
                            }
                            @*<li><a href="">Edit <i class="fa fa-edit"></i></a></li>
                                <li><a href="">Delete <i class="fa fa-trash"></i></a></li>*@
                            <li><a asp-action="index" asp-controller="ControlPanel">Cancel <i class="fa fa-ban"></i></a></li>
                            @if (Model.userP.PrintPermission)
                            {
                            <li><a href="">Print <i class="fa fa-print"></i></a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            @*<a href="#" class="btn btn-info" onclick="AddNewCity()">Add New City</a> <br /><br />*@

            <table class="table table-striped">
                <thead>
                    <tr>
                        @{
                            int sno = 0;
                        }
                        <th>SL No.</th>
                        <th>Designation</th>
                        <th>Code</th>

                        <th>Action</th>

                    </tr>
                </thead>
                <tbody id="SetDepartmentList">
                    <tr id="LoadingStatus" style="color:red"></tr>
                    @foreach (var item in Model.designationList)
                    {
                        <tr id="@item.Id">

                            <td>
                                @{ sno++; }
                                @sno
                            </td>
                            <td>@item.Name</td>
                            <td>@item.Code</td>


                            <td>
                                @if (Model.userP.UpdatePermission)
                                {
                                <a href='#' class="btn btn-primary btn-xs btn-marign-8x fa fa-edit" title="Edit" onclick="location.href='@Url.Action("EditDesignation", "ControlPanel", new { id = @item.Id })'"></a>
                                }
                                @if (Model.userP.DisplayPermission)
                                {
                                <a href='#' class="btn btn-success btn-xs btn-marign-8x fa fa-eye" title="View" onclick="location.href='@Url.Action("DesignationDeatils", "ControlPanel", new { id = @item.Id })'"></a>
                                }
                                @if (Model.userP.DeletePermission)
                                {
                                <a href='#' class="btn btn-danger btn-xs btn-marign-8x fa fa-trash" title="Delete" onclick="DesignationDelete(@item.Id)"></a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade" id="MyModal1">
    </div>


    <div class="modal fade" id="DeleteConfirmation">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h4 id="ModalTitle"></h4>
                </div>
                <div class="modal-body">
                    <h4>Are you sure? You want to delete this record.</h4>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                    <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
                </div>
            </div>
        </div>
    </div>

VehicleServiceManagement/Views/ControlPanel/EmployeeBasicInformationIndex.cshtml
@model VehicleServiceManagement.Models.EmployeeBasicInformationDisplay
    @{
        ViewData["Title"] = "EmployeeBasicInformationIndex";
        Layout = "~/Views/Shared/_ControlPanelLayout.cshtml";
    }

    <script>

    var gl_Id = 0;
    function EmployeeDelete(Id) {
        gl_Id = Id;
        $("#DeleteConfirmation").modal("show");
        }

    function ConfirmDelete() {
        var id = $("#Id").val();

        $.ajax({
            type: "POST",
            url: "/ControlPanel/EmployeeBasicInformationDelete?Id=" + gl_Id,
            success: function (data) {
                $("#DeleteConfirmation").modal("hide");
                $("table #" + id).remove();
                location.reload(true);
            }
        })

    }

    </script>
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Employee Information</h2>
        </div>
        <div class="box-body">
            <div class="row mb-7">
                <div class="col-sm-12">
                    <div class="pur-in-btn">
                        <ul>
                            @if (Model.userP.InsertPermission)
                            {
                            <li><a asp-action="CreateEmployeeBasicInformation" asp-controller="ControlPanel">New <i class="fa fa-plus"></i></a></li>
                            }
                            <li><a asp-action="index" asp-controller="ControlPanel">Cancel <i class="fa fa-ban"></i></a></li>
                            @if (Model.userP.PrintPermission)
                            {
                            <li><a href="">Print <i class="fa fa-print"></i></a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            @*<a href="#" class="btn btn-info" onclick="AddNewCity()">Add New City</a> <br /><br />*@

            <table class="table table-striped">
                <thead>
                    <tr>
                        @{
                            int sno = 0;
                        }
                        <th>SL No.</th>
                        <th>Employee Name</th>
                        <th>MobileNo</th>
                        <th>Designation</th>
                        <th>Department</th>
                        <th>Action</th>

                    </tr>
                </thead>
                <tbody id="SetDepartmentList">
                    <tr id="LoadingStatus" style="color:red"></tr>
                    @foreach (var item in Model.employeeList)
                    {
                <tr id="@item.Id">

                    <td>
                        @{ sno++; }
                        @sno
                    </td>
                    <td>@item.Name</td>
                    <td>@item.MobileNo</td>
                    <td>@item.Designation</td>
                    <td>@item.Department</td>


                    <td>
                        @if (Model.userP.UpdatePermission)
                        {
                        <a href='#' class="btn btn-primary btn-xs btn-marign-8x fa fa-edit" title="Edit" onclick="location.href='@Url.Action("EditEmployeeBasicInformation", "ControlPanel", new { id = @item.Id })'"></a>
                        }
                        @if (Model.userP.DisplayPermission)
                        {
                        <a href='#' class="btn btn-success btn-xs btn-marign-8x fa fa-eye" title="View" onclick="location.href='@Url.Action("EmployeeBasicInformationDeatils", "ControlPanel", new { id = @item.Id })'"></a>
                        }
                        @if (Model.userP.DeletePermission)
                        {
                        <a href='#' class="btn btn-danger btn-xs btn-marign-8x fa fa-trash" title="Delete" onclick="EmployeeDelete(@item.Id)"></a>
                        }
                    </td>
                </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade" id="MyModal1">
    </div>


    <div class="modal fade" id="DeleteConfirmation">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h4 id="ModalTitle"></h4>
                </div>
                <div class="modal-body">
                    <h4>Are you sure? You want to delete this record.</h4>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                    <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
                </div>
            </div>
        </div>
    </div>

VehicleServiceManagement/Views/ControlPanel/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ControlPanelLayout.cshtml";
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h2 class="box-title">Control panel</h2>
    </div>
</div>