VehicleServiceManagement/Models/OtherServiceDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace VehicleServiceManagement.Models
{
    public class OtherServiceDetails
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter  OtherService")]
        public string OtherService { get; set; }
        [Required(ErrorMessage = "Please Enter  Remark")]
        public string Remark { get; set; }


        public int create(OtherServiceDetails obj)
        {
            int i = 0;

            SqlCommand cmd;
            cmd = new SqlCommand("AddOtherServiceDetails");
            cmd.CommandType = CommandType.StoredProcedure;
            //cmd.Parameters.AddWithValue("Id", obj.Id);
            cmd.Parameters.AddWithValue("@OtherService", obj.OtherService);
           

            cmd.Parameters.AddWithValue("@Remark", obj.Remark);

            i = DbConnection.Create(cmd);
            return i;
        }
        public List<OtherServiceDetails> GetAllOtherService()
        {

            List<OtherServiceDetails> service = new List<OtherServiceDetails>();

            SqlCommand com = new SqlCommand("ReadOtherService");
            com.CommandType = CommandType.StoredProcedure;
            DataTable dt = new DataTable();
            dt = DbConnection.Read(com);
            //Bind EmpModel generic list using dataRow 
            foreach (DataRow dr in dt.Rows)
            {

                service.Add(

                    new OtherServiceDetails
                    {

                        Id = Convert.ToInt32(dr["Id"]),
                        OtherService = Convert.ToString(dr["OtherService"]),
                        Remark = Convert.ToString(dr["Remark"])
                    }
                    );
            }

            return service;

        }
        public OtherServiceDetails details(int id)
        {
            OtherServiceDetails obj = new OtherServiceDetails();
            SqlCommand com = new SqlCommand("ViewOtherServiceDetails");
            com.CommandType = CommandType.StoredProcedure;
            com.Parameters.AddWithValue("Id", id);
            DataTable dt = new DataTable();
            dt = DbConnection.Read(com);
            DataRow dr = dt.Rows[0];
            obj.Id = Convert.ToInt32(dr["Id"]);
            obj.OtherService = Convert.ToString(dr["OtherService"]);
           

            obj.Remark = Convert.ToString(dr["Remark"]);


            return (obj);


        }
        public int update(OtherServiceDetails obj)
        {
            int i = 0;

            SqlCommand cmd;
            cmd = new SqlCommand("UpdateOtherServiceDetails");
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", obj.Id);
            cmd.Parameters.AddWithValue("@OtherService", obj.OtherService);


            cmd.Parameters.AddWithValue("@Remark", obj.Remark);

            i = DbConnection.Update(cmd);
            return i;
        }
        public int delete(int id)
        {
            int i = 0;
            //City obj = new City();
            SqlCommand cmd;
            cmd = new SqlCommand("DeleteOtherServiceDetails");
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@Id", id);

            i = DbConnection.Delete(cmd);
            return i;


        }

    }

    public class OtherServiceDetailsDisplay
    {
        public List<OtherServiceDetails> otherServiceList { get; set; }
        public UserPermission userP { get; set; }
    }
}

VehicleServiceManagement/Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VehicleServiceManagement.Models;

namespace VehicleServiceManagement.Controllers
{
    public class ToolsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public PartialViewResult _partialToolLayout()
        {
            List<UserPermission> userP = new List<UserPermission>();
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            }
            UserPermission pn = new UserPermission();
            userP = pn.GetUserPermissions(UserId);

            return PartialView(userP);
        }
        public IActionResult OtherServiceDetailss(int id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "Contract").FirstOrDefault().DisplayPermission)
                {
                    OtherServiceDetails obj = new OtherServiceDetails();
                    OtherServiceDetails dealer;
                    dealer = obj.details(id);
                    return View(dealer);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult OtherServiceDetailsIndex()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "OtherService").FirstOrDefault().DisplayPermission)
                {
                    OtherServiceDetails service = new OtherServiceDetails();
                    OtherServiceDetailsDisplay displayList = new OtherServiceDetailsDisplay();
                    displayList.otherServiceList = service.GetAllOtherService();
                    displayList.userP = UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "OtherService").FirstOrDefault();
                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult OtherServiceDetailsCreate()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "OtherService").FirstOrDefault().InsertPermission)
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public IActionResult OtherServiceDetailsCreate(OtherServiceDetails service)
        {

            OtherServiceDetails obj = new OtherServiceDetails();
            obj.create(service);
            return RedirectToAction("OtherServiceDetailsIndex");
        }

        public IActionResult EditOtherServiceDetails(int id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "OtherService").FirstOrDefault().UpdatePermission)
                {
                    OtherServiceDetails obj = new OtherServiceDetails();
                    OtherServiceDetails dealer;
                    dealer = obj.details(id);
                    return View(dealer);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public IActionResult EditOtherServiceDetails(OtherServiceDetails dealer)
        {
            OtherServiceDetails obj = new OtherServiceDetails();

            obj.update(dealer);
            return RedirectToAction("OtherServiceDetailsIndex");
        }
        public JsonResult DeleteOtherServiceDetails(int Id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "OtherService").FirstOrDefault().DeletePermission)
                {
                    OtherServiceDetails obj1 = new OtherServiceDetails();
                    var result = true;
                    obj1.delete(Id);
                    return Json(result);
                }
            }
            return Json(false);
        }
        public IActionResult ManufactureCutOffInformationDetails(int id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "ManufacturerCutoff").FirstOrDefault().DisplayPermission)
                {
                    ManufactureCutOffInformation obj = new ManufactureCutOffInformation();
                    MakeDetail info = new MakeDetail();
                    var c = info.GetAllMakeDetail();
                    ViewBag.make = new SelectList(c, "Id", "Make");
                    ProductGroups info1 = new ProductGroups();
                    var c1 = info1.GetAllProductGroups();
                    ViewBag.Product = new SelectList(c1, "Id", "ProductGroup");
                    ManufactureCutOffInformation dealer;
                    dealer = obj.details(id);
                    return View(dealer);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult ManufactureCutOffInformationIndex()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "ManufacturerCutoff").FirstOrDefault().DisplayPermission)
                {
                    ManufactureCutOffInformation service = new ManufactureCutOffInformation();
                    MakeDetail info = new MakeDetail();
                    var c = info.GetAllMakeDetail();
                    ViewBag.make = new SelectList(c, "Id", "Make");
                    ProductGroups info1 = new ProductGroups();
                    var c1 = info1.GetAllProductGroups();
                    ViewBag.Product = new SelectList(c1, "Id", "ProductGroup");
                    ManufactureCutoffInformationDisplay displayList = new ManufactureCutoffInformationDisplay();
                    displayList.cutoffList = service.GetAllManufacturCutoff();
                    displayList.userP = UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "ManufacturerCutoff").FirstOrDefault();
                    return View(displayList);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult ManufactureCutOffInformationCreate()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "ManufacturerCutoff").FirstOrDefault().InsertPermission)
                {
                    MakeDetail info = new MakeDetail();
                    var c = info.GetAllMakeDetail();
                    ViewBag.make = new SelectList(c, "Id", "Make");
                    ProductGroups info1 = new ProductGroups();
                    var c1 = info1.GetAllProductGroups();
                    ViewBag.Product = new SelectList(c1, "Id", "ProductGroup");
                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public IActionResult ManufactureCutOffInformationCreate(ManufactureCutOffInformation service)
        {

            ManufactureCutOffInformation obj = new ManufactureCutOffInformation();
            obj.create(service);
            return RedirectToAction("ManufactureCutOffInformationIndex");
        }

        public IActionResult EditManufactureCutOffInformation(int id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "ManufacturerCutoff").FirstOrDefault().UpdatePermission)
                {

VehicleServiceManagement/Views/Tools/CCRangeIndex.cshtml
@model VehicleServiceManagement.Models.CCRangeDisplay

@{
    ViewData["Title"] = "CCRangeIndex";
    Layout = "~/Views/Shared/_ToolLayout.cshtml";
}


<script>
    var gl_Id = 0;
    function Deleteccrange(Id) {
        gl_Id = Id;
        $("#DeleteConfirmation").modal("show");
    }
    function ConfirmDelete() {
        var id = $("#Id").val();
        $.ajax({
            type: "POST",
            url: "/Tools/DeleteCCRange?Id=" + gl_Id,
            success: function (data) {
                $("#DeleteConfirmation").modal("hide");
                $("table #" + id).remove();
                location.reload(true);
            }
        })

    }

/**/</script>


<div class="box box-primary">
    <div class="box-header with-border">
        <h2 class="box-title">CC Range Information</h2>
    </div>
    <div class="box-body">
        <div class="row mb-7">
            <div class="col-sm-12">
                <div class="pur-in-btn">
                    <ul>
                        @if (Model.userP.InsertPermission)
                        {
                        <li><a asp-action="CCRangeCreate" asp-controller="Tools">New <i class="fa fa-plus"></i></a></li>
                        }
                        @*<li><a href="/MasterManagement/CCRangeEdit">Edit <i class="fa fa-edit"></i></a></li>
                        <li><a href="">Delete <i class="fa fa-trash"></i></a></li>*@
                        <li><a asp-action="index" asp-controller="Tools">Cancel <i class="fa fa-ban"></i></a></li>
                        @if (Model.userP.PrintPermission)
                        {
                        <li><a href="">Print <i class="fa fa-print"></i></a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped m-0">
                        <thead>
                            <tr>

                                @{
                                    int sno = 0;
                                }

                                <th>SL No.</th>
                                <th>CC Range</th>
                                <th>Category Name</th>
                                <th>Dealer Name</th>
                               @* <th>Remarks</th>*@

                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody id="">
                            <tr id="" style="color:red"></tr>
                            @foreach (var item in Model.ccrangeList)
                            {
                                <tr id="@item.Id">

                                    <td>
                                        @{ sno++; }
                                        @sno
                                    </td>
                                    <td>@item.Range</td>
                                    <td>@item.CategoryName</td>
                                    @*<td>@item.CategoryName</td>*@
                                    <td>@item.Name</td>
                                    @*<td>@item.Remark</td>*@

                                    <td>
                                        @if (Model.userP.UpdatePermission)
                                        {
                                        <a href='#' class="btn btn-primary btn-xs btn-marign-8x fa fa-edit" title="Edit" onclick="location.href='@Url.Action("CCRangeEdit", "Tools", new { id = @item.Id })'"></a>
                                        }
                                        @if (Model.userP.DisplayPermission)
                                        {
                                        <a href='#' class="btn btn-success btn-xs btn-marign-8x fa fa-eye" title="View" onclick="location.href='@Url.Action("CCRangeDetails", "Tools", new { id = @item.Id })'"></a>
                                        }
                                        @if (Model.userP.DeletePermission)
                                        {
                                        <a href='#' class="btn btn-danger btn-xs btn-marign-8x fa fa-trash" title="Delete" onclick="Deleteccrange(@item.Id)"></a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="modal fade" id="MyModal1">
        </div>
        <div class="modal fade" id="DeleteConfirmation">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <a href="#" class="close" data-dismiss="modal">&times;</a>
                        <h4 id="ModalTitle"></h4>
                    </div>
                    <div class="modal-body">
                        <h4>Are you sure? You want to delete this record.</h4>
                    </div>
                    <div class="modal-footer">
                        <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                        <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

VehicleServiceManagement/Views/Tools/DurationInformationCreate.cshtml
@model VehicleServiceManagement.Models.Durations
@{
    ViewData["Title"] = "DurationInformationCreate";
    Layout = "~/Views/Shared/_ToolLayout.cshtml";
}

<form asp-controller="Tools" asp-action="DurationInformationCreate" method="post" >
    <div class="content">
        <div class="row">
            <div class="col-sm-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h2 class="box-title">Create Extend Duration</h2>
                        <div class="empl-regi">

                        </div>
                    </div>


                    <div class="box-body with-border">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="empl-regi">
                                    <div class="tab-content">
                                        <div id="bi" class="tab-pane fade in active">
                                            


                                            <div class="row mb-5">
                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <label class="col-md-5 control-label no-padding">Extend Duration:<label style="color:red">*</label></label>
                                                         <div class="col-md-7">
                                                           
                                                             <input asp-for="objval.Duration" required class="form-control form-control-spl" />
                                                                @Html.ValidationMessageFor(model => model.objval.Duration, "", new { @class = "text-danger" })
                                                          </div>                                                            
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row mb-5">

                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <label class="col-md-5 control-label no-padding">Product SubGroupName:<label style="color:red">*</label></label>
                                                        <div class="col-md-7">
                                                            @Html.DropDownListFor(m => m.objval.SubGroupId, (IEnumerable<SelectListItem>)ViewBag.sg, "-- Select Product Sub Group--", new { required = "required", @name = "SubGroupId", @class = "form-control form-control-spl", @placeholder = "type*" })
                                                            @Html.ValidationMessageFor(model => model.objval.SubGroupId, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>

                                            <div class="row mb-5">
                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <label class="col-md-5 control-label no-padding">Category:<label style="color:red">*</label></label>
                                                        <div class="col-md-7">
                                                            @Html.DropDownListFor(m => m.objval.CategoryId, (IEnumerable<SelectListItem>)ViewBag.cat, "-- Select category--", new { required = "required", @id = "type", @class = "form-control form-control-spl", @placeholder = "type*" })
                                                            @Html.ValidationMessageFor(model => model.objval.CategoryId, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                </div>                                              
                                            </div>

                                            <div class="row mb-5">
                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <label class="col-md-5 control-label no-padding">Remark:</label>
                                                        <div class="col-md-7">
                                                            @*<input asp-for="objval.Remark" required class="form-control form-control-spl" />*@
                                                            <textarea asp-for="objval.Remark" required class="form-control form-control-spl" style="height:auto !important; max-width:100%; width:100%;" rows="3"></textarea>
                                                            @Html.ValidationMessageFor(model => model.objval.Remark, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                </div>                                             
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="form-group">
                        <div class="pull-right">
                            <button type="submit" id="submit" class="btn btn-primary">Save & Done</button>
                            <button type="button" class="btn btn-success">Save & New</button>
                            <input type="button" class="btn btn-primary btn-danger" value="Cancel" onclick="history.back()">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

VehicleServiceManagement/Views/Tools/PremiumIndex.cshtml
    @model VehicleServiceManagement.Models.PremiumDisplay
    @{
        ViewData["Title"] = "PremiumIndex";
        Layout = "~/Views/Shared/_ToolLayout.cshtml";
    }

    <script>       
        var gl_Id = 0;
        function DealerBranchDelete(Id) {
            gl_Id = Id;
            $("#DeleteConfirmation").modal("show");
        }
        function ConfirmDelete() {
            var id = $("#Id").val();

            $.ajax({
                type: "POST",
                url: "/Tools/PremiumDelete?Id=" + gl_Id,
                success: function (data) {
                    $("#DeleteConfirmation").modal("hide");
                    $("table #" + id).remove();
                    location.reload(true);
                }
            })

        }
        /**/</script>
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title"> Premium Information Index</h2>
        </div>
        <div class="box-body">
            <div class="row mb-7">
                <div class="col-sm-12">
                    <div class="pur-in-btn">
                        <ul>
                            @if (Model.userP.InsertPermission)
                            {
                            <li><a asp-action="PremiumCreate" asp-controller="Tools">New <i class="fa fa-plus"></i></a></li>
                            }
                            @*<li><a href="">Edit <i class="fa fa-edit"></i></a></li>
                            <li><a href="">Delete <i class="fa fa-trash"></i></a></li>*@
                            <li><a asp-action="Index" asp-controller="Tools">Cancel <i class="fa fa-ban"></i></a></li>
                            @if (Model.userP.PrintPermission)
                            {
                            <li><a href="">Print <i class="fa fa-print"></i></a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            @*<a href="#" class="btn btn-info" onclick="AddNewCity()">Add New City</a> <br /><br />*@

            <table class="table table-striped">
                <thead>
                    <tr>
                        @{
                            int sno = 0;
                        }
                        <th>SL No.</th>
                        <th>Dealer</th>
                        <th>Extend Duration</th>
                        <th>From Date</th>
                        <th>To Date</th>
                        <th>Premium Amount</th>
                        <th>Action</th>

                    </tr>
                </thead>
                <tbody id="SetDepartmentList">
                    <tr id="LoadingStatus" style="color:red"></tr>
                    @foreach (var item in Model.premiumList)
                    {
                    <tr id="@item.Id">

                        <td>
                            @{ sno++; }
                            @sno
                        </td>
                        <td>@item.Name</td>
                        <td>@item.Duration</td>
                        <td>@item.FromDate</td>
                        <td>@item.ToDate</td>
                        <td>@item.PremiumAmount</td>

                        <td>
                            @if (Model.userP.UpdatePermission)
                            {
                            <a href='#' class="btn btn-primary btn-xs btn-marign-8x fa fa-edit" title="Edit" onclick="location.href='@Url.Action("PremiumEdit", "Tools", new { id = @item.Id })'"></a>
                            }
                            @if (Model.userP.DisplayPermission)
                            {
                            <a href='#' class="btn btn-success btn-xs btn-marign-8x fa fa-eye" title="View" onclick="location.href='@Url.Action("PremiumDetails", "Tools", new { id = @item.Id })'"></a>
                            }
                            @if (Model.userP.DeletePermission)
                            {
                            <a href='#' class="btn btn-danger btn-xs btn-marign-8x fa fa-trash" title="Delete" onclick="DealerBranchDelete(@item.Id)"></a>
                            }
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade" id="MyModal1">
    </div>


    <div class="modal fade" id="DeleteConfirmation">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h4 id="ModalTitle"></h4>
                </div>
                <div class="modal-body">
                    <h4>Are you sure? You want to delete this record.</h4>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                    <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
                </div>
            </div>
        </div>
    </div>