VehicleServiceManagement/Controllers/VATController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccounTechSoftware.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VehicleServiceManagement.Models;

namespace VehicleServiceManagement.Controllers
{
    public class VATController : Controller
    {
        public IActionResult Index()
        {
            //ViewBag.companyname = HttpContext.Session.GetString("CompanyName");
            return View();
        }
        public PartialViewResult _partialVATLayout()
        {
            List<UserPermission> userP = new List<UserPermission>();
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            }
            UserPermission pn = new UserPermission();
            userP = pn.GetUserPermissions(UserId);

            return PartialView(userP);
        }
        public IActionResult VatCategoryIndex()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "VATCategory").FirstOrDefault().DisplayPermission)
                {
                    VatCategory obj = new VatCategory();
                    VatCategory vat = new VatCategory();
                    List<VatCategory> dep = new List<VatCategory>();
                    dep = obj.GetAllVat().ToList();
                    //ViewBag.companyname = HttpContext.Session.GetString("CompanyName");
                    vat.vatCategories = dep;
                    vat.userP = UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "VATCategory").FirstOrDefault();
                    return View(vat);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public IActionResult CreateVatCategory(VatCategory vat)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "VATCategory").FirstOrDefault().InsertPermission)
                {
                    VatCategory obj = new VatCategory();
                    obj.create(vat);
                    return RedirectToAction("VatCategoryIndex");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult EditVatCategory(int Id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "VATCategory").FirstOrDefault().UpdatePermission)
                {
                    VatCategory obj = new VatCategory();
                    VatCategory vat;
                    vat = obj.GetbyId(Id);
                    List<VatCategory> vatlist = new List<VatCategory>();
                    vatlist = vat.GetAllVat().ToList();
                    return PartialView("_VatcategoryEdit", vat);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public IActionResult EditVatCategory(VatCategory vat)
        {
            VatCategory obj = new VatCategory();
            obj.update(vat);
            return RedirectToAction("VatCategoryIndex");
        }

        public JsonResult Delete(int Id)
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "VATCategory").FirstOrDefault().DeletePermission)
                {
                    VatCategory obj = new VatCategory();
                    var result = true;
                    obj.delete(Id);
                    return Json(result);
                }
            }
            return Json(false);
        }
    }

}

VehicleServiceManagement/Views/VAT/Index.cshtml
@{
    ViewData["Title"] = "Index";
     Layout = "~/Views/Shared/_VATLayout.cshtml";
}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Value Added Tax (VAT) Information Dashboard</h2>
        </div>
    </div>

VehicleServiceManagement/Views/VAT/VatCategoryIndex.cshtml
@model AccounTechSoftware.Models.VatCategory

@{
    ViewData["Title"] = "VatCategoryIndex";
     Layout = "~/Views/Shared/_VATLayout.cshtml";
}

<script>

    function AddNewVatCategory() {


        $("#ModalTitle").html("Add New VatCategory");
        $("#ModalTitle").show();
        $("#MyModal").modal();
    }

    function EditVatCategoryRecord(Id) {

        var url = "/VAT/EditVatCategory?Id=" + Id;

        $.ajax({
            type: "GET",
            url: url,

            success: function (data) {
                $('#MyModal1').html(data);
                $('#MyModal1').modal("show");

            }
        })

    }

    function DeleteVatCategoryRecord(Id) {
        $("#Id").val(Id);
        $("#DeleteConfirmation").modal("show");
    }
    function ConfirmDelete() {
        var id = $("#Id").val();

        $.ajax({
            type: "POST",
            url: "/VAT/Delete?Id=" + id,
            success: function (data) {
                $("#DeleteConfirmation").modal("hide");
                $("table #" + id).remove();

            }
        })

    }
      $(document).on('keydown', ':tabbable', function (e) {

             if (e.key === "Enter") {
                 e.preventDefault();

                 var $canfocus = $(':tabbable:visible');
                 var index = $canfocus.index(document.activeElement) + 1;

                 if
                     (index >= $canfocus.length) index = 0;
                 $canfocus.eq(index).focus();
             }


   });
</script>

<div class="box box-primary">
    <div class="box-header with-border">
        <h2 class="box-title">VAT Category Information</h2>
    </div>
    <div class="box-body">
        <div class="row mb-7">
            <div class="col-sm-12">
                <div class="pur-in-btn">
                    <ul>
                        @*<li><a href="#" onclick="AddNewVatCategory()">New <i class="fa fa-plus"></i></a></li>
                        <li><a href="">Edit <i class="fa fa-edit"></i></a></li>
                        <li><a href="">Delete <i class="fa fa-trash"></i></a></li>*@
                        <li><a href="">Cancel <i class="fa fa-ban"></i></a></li>
                        @if (Model.userP.PrintPermission)
                        {
                        <li><a href="">Print <i class="fa fa-print"></i></a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>


        @*<a href="#" class="btn btn-info" onclick="AddNewDepartment()">Add New Department</a> <br /><br />*@

        <table class="table table-striped">
            <thead>
                 <tr>
                    @{
                        int sno = 0;
                    }
                     <th>SLNo</th>
                    <th>Code</th>
                    <th>Category</th>
                    <th>Rate Perscent</th>
                    <th>Description</th>
                    @*<th>Action(Edit)</th>
                    <th>Action(Delete)</th>*@
            </thead>
            <tbody id="SetDepartmentList">
                <tr id="LoadingStatus" style="color:red"></tr>
                @foreach (var item in Model.vatCategories)
                {
             <tr id="@item.VatId">
                <td>
                    @{ sno++; }
                    @sno
                </td>
                <td>@item.Code</td>
                <td>@item.Category</td>
                <td>@item.RatePerscent</td>
                <td>@item.Description</td>

               @* <td><a href='#' class="btn btn-warning btn-xs btn-marign-8x" onclick="EditVatCategoryRecord(@item.VatId)">Edit</a></td>
                <td><a href='#' class="btn btn-danger btn-xs btn-marign-8x" onclick="DeleteVatCategoryRecord(@item.VatId)">Delete</a></td>*@
            </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@*Create POPUP for new form*@
<div class="modal fade" id="MyModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h4 id="ModalTitle">Add New Group</h4>


            </div>
            <div class="modal-body">
                <form asp-controller="VAT" asp-action="CreateVatCategory" method="post">

                    <fieldset id="SubmitForm">
                        @Html.HiddenFor(m => m.VatId, new { @id = "Id" })

                        <div class="form-regi">
                            <ul>
                                <li>
                                    <label>Code</label>
                                </li>
                                <li>
                                    @Html.TextBoxFor(m => m.Code, new { @id = "Code", @class = "form-control", @placeholder = "Code*" })
                                </li>
                            </ul>

                        </div>
                        <div class="form-regi">
                            <ul>
                                <li>
                                    <label>Category</label>
                                </li>
                                <li>
                                    @Html.TextBoxFor(m => m.Category, new { @id = "Category", @class = "form-control", @placeholder = "Category*" })
                                </li>
                            </ul>

                        </div>
                        <div class="form-regi">
                            <ul>
                                <li>
                                    <label>RatePerscent</label>
                                </li>
                                <li>
                                    @Html.TextBoxFor(m => m.RatePerscent, new { @id = "RatePerscent", @class = "form-control", @placeholder = "RatePerscent*" })
                                </li>
                            </ul>

                        </div>
                        <div class="form-regi">
                            <ul>
                                <li>
                                    <label>Description</label>
                                </li>
                                <li>
                                    @Html.TextBoxFor(m => m.Description, new { @id = "Description", @class = "form-control", @placeholder = "Description*" })
                                </li>
                            </ul>

                        </div>
                      <br /><br />
                        <div class="form-regi">
                            <div class="form-regi">
                                <div class="col-sm-12">

                                    <div class="col-sm-6">
                                        <br /><br />
                                        <button type="submit" class="btn btn-block btn-success" id="submit">Save</button>
                                    </div>
                                    <div class="col-sm-6">
                                        <br /><br />
                                        <button type="button" class="btn btn-block btn-danger" onclick="TextBoxclear()" id="clear">Clear</button>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>



@*Create POPUP for edit form*@
<div class="modal fade" id="MyModal1">
</div>


<div class="modal fade" id="DeleteConfirmation">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h4 id="ModalTitle"></h4>
            </div>
            <div class="modal-body">
                <h4>Are you sure? You want to delete this record.</h4>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-primary" data-dismiss="modal">Cancel</a>
                <a href="#" class="btn btn-danger" onclick="ConfirmDelete()">Confirm</a>
            </div>
        </div>
    </div>
</div>
<script>
        $("#submit1").click(function () {

            ShowAlertPopup('Created Successfully ', 'Success', ALERT_TYPE_GREEN);

        });</script>

VehicleServiceManagement/Views/VAT/_VatcategoryEdit.cshtml
@model AccounTechSoftware.Models.VatCategory
@{
    Layout = null;
}


<!DOCTYPE html>


<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <a href="#" class="close" data-dismiss="modal">&times;</a>
            <h4 id="ModalTitle1"></h4>
        </div>
        <div class="modal-body">
            <form asp-controller="VAT" asp-action="EditVatCategory" method="post">
                <fieldset id="SubmitForm">
                    @Html.HiddenFor(m => m.VatId, new { @id = "Id" })

                    <div class="form-regi">
                        <ul>
                            <li>
                                <label>Code</label>
                            </li>
                            <li>
                                @Html.TextBoxFor(m => m.Code, new { @id = "Code", @class = "form-control", @placeholder = "Code*" })
                            </li>
                        </ul>

                    </div>
                    <div class="form-regi">
                        <ul>
                            <li>
                                <label>Category</label>
                            </li>
                            <li>
                                @Html.TextBoxFor(m => m.Category, new { @id = "Category", @class = "form-control", @placeholder = "Category*" })
                            </li>
                        </ul>

                    </div>
                    <div class="form-regi">
                        <ul>
                            <li>
                                <label>RatePerscent</label>
                            </li>
                            <li>
                                @Html.TextBoxFor(m => m.RatePerscent, new { @id = "RatePerscent", @class = "form-control", @placeholder = "RatePerscent*" })
                            </li>
                        </ul>

                    </div>
                    <div class="form-regi">
                        <ul>
                            <li>
                                <label>Description</label>
                            </li>
                            <li>
                                @Html.TextBoxFor(m => m.Description, new { @id = "Description", @class = "form-control", @placeholder = "Description*" })
                            </li>
                        </ul>

                    </div>




                    <br /><br />
                    <div class="form-regi">
                        <button type="submit" class="btn btn-block btn-danger" id="submit1">Save</button>
                    </div>


                </fieldset>
            </form>
        </div>
    </div>
</div>
<script>
        $("#submit1").click(function () {

            ShowAlertPopup('Updated Successfully ', 'Success', ALERT_TYPE_GREEN);

        });
      $(document).on('keydown', ':tabbable', function (e) {

             if (e.key === "Enter") {
                 e.preventDefault();

                 var $canfocus = $(':tabbable:visible');
                 var index = $canfocus.index(document.activeElement) + 1;

                 if
                     (index >= $canfocus.length) index = 0;
                 $canfocus.eq(index).focus();
             }


   });
</script>