VehicleServiceManagement/Models/Accounts/JournalVoucherDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VehicleServiceManagement.Models.Accounts
{
    public class JournalVoucherDetails
    {
        public long Id { get; set; }
        public long JVId { get; set; }       
        [Required(ErrorMessage = "Field required Account")]
        public int LedgerId { get; set; }
        public string LedgerName { get; set; }
        public string Narration { get; set; }
        public float DrAmount { get; set; }
        public float CrAmount { get; set; }
        public float Balance { get; set; }
        public string UID { get; set; }

    }
}

VehicleServiceManagement/Models/Accounts/PaymentVoucherDetails.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace VehicleServiceManagement.Models.Accounts
{
    public class PaymentVoucherDetails
    {
        public int Id { get; set; }
        public long PaymentMasterId { get; set; }
        public long VoucherNo { get; set; }
        public DateTime Date { get; set; }
        public string VendorInvoice { get; set; }
        public float InvoiceAmount { get; set; }
        public float PrevPaid { get; set; }
        public float Balance { get; set; }
        public float Discount { get; set; }
        public float PaidAmount { get; set; }
        public Boolean FullyPaid { get; set; }
        
        public List<PaymentVoucherDetails> GetDetailsByVendor(long LedgerId)
        {

            List<PaymentVoucherDetails> objlist = new List<PaymentVoucherDetails>();
            SqlCommand com = new SqlCommand("GetPaymentByVendor");
            com.CommandType = CommandType.StoredProcedure;
            com.Parameters.AddWithValue("@LedgerId", LedgerId);
            DataTable dt = new DataTable();
            dt = DbConnection.Read(com);
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                PaymentVoucherDetails obj = new PaymentVoucherDetails();              
                obj.VoucherNo = Convert.ToInt64(dt.Rows[i]["VoucherNo"]);
                obj.Date = Convert.ToDateTime(dt.Rows[i]["Date"]);
                obj.VendorInvoice = Convert.ToString(dt.Rows[i]["VendorInvoice"]);
                obj.InvoiceAmount = float.Parse(dt.Rows[i]["InvoiceAmount"].ToString());
                obj.PrevPaid = float.Parse(dt.Rows[i]["PrevPaid"].ToString());
                obj.Balance = obj.InvoiceAmount - obj.PrevPaid;
                objlist.Add(obj);
            }           
            return objlist;
        }

    }
}

VehicleServiceManagement/Controllers/FinancialController.cs
using AccounTechSoftware.Models;
using VehicleServiceManagement.Models;
using VehicleServiceManagement.Models.Accounts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using static VehicleServiceManagement.Models.Accounts.ClsAccountTransaction;
using BusinessSoftware.Models;
using Microsoft.AspNetCore.Http;

namespace VehicleServiceManagement.Controllers
{
    public class FinancialController : Controller
    {

        public static string[] StatusType = new string[] { "Pending", "Completed", "Rejected" };
        private IMemoryCache _cache;
        private static string Guid;
        JournalVoucher obj = new JournalVoucher();
        PaymentVoucher obj1 = new PaymentVoucher();
        ClsSubGroup obj2 = new ClsSubGroup();
        public FinancialController(IMemoryCache memoryCache)
        {
            _cache = memoryCache;
        }
        public static string[] CreditDebit = new string[] { "Credit", "Debit"};
        public IActionResult Index()
        {           
            return View();
        }
        public PartialViewResult _partialFinancialLayout()
        {
            List<UserPermission> userP = new List<UserPermission>();
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
            }
            UserPermission pn = new UserPermission();
            userP = pn.GetUserPermissions(UserId);

            return PartialView(userP);
        }

        public IActionResult ChartofAccIndex()
        {
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "ChartOfAccounts").FirstOrDefault().DisplayPermission)
                {
                    ClsChartofAccount obj = new ClsChartofAccount();
                    return View(obj.GetChartOfAccount());
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");

        }
       
        public IActionResult subgroupDetails(string Id)
        {
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "AccountsGroup").FirstOrDefault().DisplayPermission)
                {
                    Clsledger obj = new Clsledger();
                    return PartialView("_SubGroupDetails", obj.GetAccountBySubGroup(Convert.ToInt32(Id)));
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }

        public IActionResult EditSubGroup(int Id)
        {
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "AccountsGroup").FirstOrDefault().UpdatePermission)
                {
                    ClsSubGroup sgroup;
                    sgroup = obj2.details(Id);
                    List<ClsSubGroup> clsList = new List<ClsSubGroup>();
                    clsList = sgroup.GetAllSubGroup().ToList();
                    return PartialView("EditSubGroup", sgroup);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public IActionResult EditSubGroup(ClsSubGroup sgroup)
        {
            obj2.update(sgroup);
            ViewBag.successmessage = "SubGroup Information Updated Successfully !!!";
            ClsSubGroup objsubgroup = new ClsSubGroup();
            List<ClsSubGroup> c = new List<ClsSubGroup>();
            c = obj2.GetAllSubGroup().ToList();
            objsubgroup.clsList = c;
            //ViewBag.companyname = HttpContext.Session.GetString("CompanyName");
            return View("SubGroupIndex", objsubgroup);
        }

        public JsonResult DeleteSubGroup(int Id)
        {
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "AccountsGroup").FirstOrDefault().DeletePermission)
                {
                    var result = true;
                    obj2.delete(Id);
                    return Json(result);
                }
            }
            return Json(false);
        }

        public IActionResult SubGroupIndex()
        {
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "AccountsGroup").FirstOrDefault().DisplayPermission)
                {
                    //ClsSubGroup obj1= new ClsSubGroup();
                    ClsSubGroup sub = new ClsSubGroup();
                    List<ClsSubGroup> c = new List<ClsSubGroup>();
                    c = obj2.GetAllSubGroup().ToList();
                    sub.clsList = c;
                    sub.userP = UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "AccountsGroup").FirstOrDefault();
                    ClsGroup group = new ClsGroup();
                    var d = group.GetAllGroup();
                    ViewBag.group = new SelectList(d, "Id", "Name");
                    //ViewBag.companyname = HttpContext.Session.GetString("CompanyName");
                    return View(sub);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public IActionResult SubGroupCreate(ClsSubGroup sub)
        {
            int UserId = 0;
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "AccountsGroup").FirstOrDefault().InsertPermission)
                {
                    //ClsSubGroup obj2 = new ClsSubGroup();
                    obj2.create(sub);
                    return RedirectToAction("SubGroupIndex");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");

        }
         
        public IActionResult JournalVoucherIndex()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "JournalVoucher").FirstOrDefault().DisplayPermission)
                {
                    JournalVoucherMaster master = new JournalVoucherMaster();
                    //ViewBag.companyname = HttpContext.Session.GetString("CompanyName");
                    JournalVoucherMasterDisplay displayList = new JournalVoucherMasterDisplay();
                    displayList.journalVoucherList = master.GetJournalVoucherMaster();
                    displayList.userP = UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "JournalVoucher").FirstOrDefault();
                    return View(displayList);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }

        public IActionResult JournalVoucherCreate()
        {
            if (HttpContext.Session.GetInt32("UserId") != null)
            {
                int UserId = Convert.ToInt32(HttpContext.Session.GetInt32("UserId"));
                if (UserPermission.permissionList.Where(a => a.UserId == UserId && a.FormName == "JournalVoucher").FirstOrDefault().InsertPermission)
                {
                    Clsledger acc = new Clsledger();
                    var c1 = acc.GetAllLedger();
                    ViewBag.ledger = new SelectList(c1, "Id", "Name");

                    Location loc = new Location();
                    var c2 = loc.GetLocationName();
                    ViewBag.location = new SelectList(c2, "Id", "LocationName");

                    EmployeeBasicInformation emp = new EmployeeBasicInformation();
                    var c3 = emp.GetEmployeeMaster();
                    ViewBag.Employee = new SelectList(c3, "Id", "Name");

                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Login", "Home");
        }

        public JsonResult SetJournalVoucher(JournalVoucherDetails prdtdetails)
        {

            StringBuilder str = new StringBuilder();
            Guid = prdtdetails.UID;

VehicleServiceManagement/Views/Financial/CheckPaymentCreate.cshtml
@model VehicleServiceManagement.Models.Accounts.CheckPayment

@{
    ViewData["Title"] = "CheckPaymentCreate";
    Layout = "~/Views/Shared/_FinancialLayout.cshtml";
}

VehicleServiceManagement/Views/Financial/JournalVoucherDetails.cshtml
@model VehicleServiceManagement.Models.Accounts.JournalVoucher

@{
    ViewData["Title"] = "JournalVoucherCreate";
    Layout = "~/Views/Shared/_FinancialLayout.cshtml";
}
@*<script src="~/js/RandomNumber.js"></script>*@
@*<script src="~/js/BlurTextBox.js"></script>*@
<input type="hidden" id="LocationName" onblur="HideBorder()" />
<input type="hidden" id="CurrencyName" onblur="HideBorder()" />
<br /><br />

<h4>&nbsp;&nbsp;&nbsp;JournalVoucher Details</h4>
<form asp-controller="Financial" asp-action="JournalVoucherDetails" method="post" class="form-inline" id="formId">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="/Financial/JournalVoucherIndex" class="previous">&laquo; Previous</a>

    <div class="row">
        <div class="col-md-6">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JournalVoucherMaster.Id" class="control-label col-sm-4"></label>
                <input asp-for="JournalVoucherMaster.Id" id="a" class="form-control-sm col-sm-8 " />
                <span asp-validation-for="JournalVoucherMaster.Id" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="JournalVoucherMaster.LocationId" class="control-label col-sm-4"></label>
                @*<input asp-for="JournalVoucherMaster.Location" id="VoucherNo" class="form-control col-sm-8 " />*@
                @Html.DropDownListFor(m => m.JournalVoucherMaster.LocationId, (IEnumerable<SelectListItem>)ViewBag.location, "--Select--", new { @id = "LocationId", @class = "form-control form-control-sm col-sm-8" })
                <span asp-validation-for="JournalVoucherMaster.LocationId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="JournalVoucherMaster.Status" class="control-label "></label>
                <input asp-for="JournalVoucherMaster.Status" class="form-control-sm col-sm-8 " />
                <span asp-validation-for="JournalVoucherMaster.Status" class="text-danger"></span>
            </div>

        </div>
        <br />
        <br />
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="JournalVoucherMaster.Date" class="control-label col-sm-4"></label>
                <input asp-for="JournalVoucherMaster.Date" data-required-message="Required Field" required id="Date" class="form-control-sm  col-sm-8 " />
                <span asp-validation-for="JournalVoucherMaster.Date" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="JournalVoucherMaster.Reference" class="control-label col-sm-4"></label>
                <input asp-for="JournalVoucherMaster.Reference" id="Date" class="form-control-sm  col-sm-8 " />
                <span asp-validation-for="JournalVoucherMaster.Reference" class="text-danger"></span>
            </div>
        </div>
    </div>



    <div class="container" style="margin-top:3%">
        <table id="tblIndex" class="table table-striped table-responsive table-bordered">
            <thead>
                <tr>
                    <th>Account</th>
                    <th>Narration</th>
                    <th>Location</th>                   
                    <th>DrAmount</th>
                    <th>CrAmount</th>
                    <th>Balance</th>
                </tr>
            </thead>
            <tbody></tbody>


            <tfoot>
                <tr>
                    <td>@Html.DropDownList("LedgerId", (IEnumerable<SelectListItem>)ViewBag.ledger, "--select--", new { @class = "form-control form-control-sm col-sm-12" }) </td>
                    <td><input type="text" id="Narration" style="width:100%" class="form-control col-sm-12" /></td>
                    <td>@Html.DropDownList("b", (IEnumerable<SelectListItem>)ViewBag.location, "--select--", new { @class = "form-control form-control-sm col-sm-12" }) </td>
                    <td><input type="number" id="DrAmount" style="width:100%" value="0" class="form-control col-sm-12" /></td>
                    <td>
                        <input type="number" id="CrAmount" style="width:100%" value="0" class="form-control col-sm-12" />
                    </td>
                    <td><input type="number" id="BalanceAmount" style="width:100%" value="0" class="form-control col-sm-12" /></td>
                </tr>
            </tfoot>

        </table>
    </div>
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <div class="form-group">
                <label asp-for="JournalVoucherMaster.Remarks" class="control-label col-sm-4"></label>

                <input asp-for="JournalVoucherMaster.Remarks" class="form-control col-sm-8 " />
                <span asp-validation-for="JournalVoucherMaster.Remarks" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-4">
            <br />
            <table style="border:groove">
                <tr>
                    <td>TotalDebit</td>
                    <td> @Html.TextBox("TotalDebit", "0", new { @class = "form-control" })</td>
                </tr>
                <tr></tr>
                <tr>
                    <td>TotalCredit</td>
                    <td> @Html.TextBox("TotalCredit", "0", new { @class = "form-control" })</td>
                </tr>

            </table>
            <br />

            <input type="submit" value="Create" class="btn btn-info" />
        </div>
    </div>
    <div class="form-group">
        @Html.HiddenFor(m => m.JournalVoucherMaster.TotalDebit, new { @id = "DebitTotal" })
    </div>
    <div class="form-group">
        @Html.HiddenFor(m => m.JournalVoucherMaster.TotalCredit, new { @id = "CreditTotal" })
    </div>
</form>
<input type="hidden" id="CurrencyId" />
<script>

    $(document).ready(function () {
        var totalDebit = parseFloat($("#DebitTotal").val());
        var totalCredit = parseFloat($("#CreditTotal").val());
        $("#TotalDebit").val(totalDebit);
        $("#TotalCredit").val(totalCredit);
        $("#DebitTotal").val(totalDebit);
        $("#CreditTotal").val(totalCredit);
        getdetails();

    });


  
    function getdetails() {

        var uid = $('#UID').val();
        var no = $("#a").val();


        $.ajax({
            type: "POST",
            url: "/Financial/EditJournalVoucherproduct",
            data: { no, uid, },

            success: function (response) {
                $('#tblIndex tbody').html(response.data);
                $("#LedgerId").focus();
                $("#b").val("");
                $("#Account").val("");            
                $("#Narration").val("");              
                $("#DrAmount").val("0");
                $("#CrAmount").val("0");
                $("#BalanceAmount").val("0");
            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        })
    }




</script>
<input type="hidden" value="@Guid.NewGuid().ToString()" id="UID" />

VehicleServiceManagement/Views/Financial/JournalVoucherIndex.cshtml
@model VehicleServiceManagement.Models.Accounts.JournalVoucherMasterDisplay

@{
    ViewData["Title"] = "JournalVoucherIndex";
    Layout = "~/Views/Shared/_FinancialLayout.cshtml";
}
<div class="box box-primary">
    <div class="box-header with-border">
        <h2 class="box-title">Journal Voucher Information</h2>
    </div>
    <div class="box-body">
        <div class="row mb-7">
            <div class="col-sm-12">
                <div class="pur-in-btn">
                    <ul>
                        @if (Model.userP.InsertPermission)
                        {
                        <li><a asp-action="JournalVoucherCreate" asp-controller="Financial">New <i class="fa fa-plus"></i></a></li>
                        }
                        @*<li><a href="/Financial/JournalVoucherEdit">Edit <i class="fa fa-edit"></i></a></li>
                        <li><a href="/Financial/JournalVoucherDelete">Delete <i class="fa fa-trash"></i></a></li>*@
                        <li><a asp-action="index" asp-controller="Financial">Cancel <i class="fa fa-ban"></i></a></li>
                        @if (Model.userP.PrintPermission)
                        {
                        <li><a href="">Print <i class="fa fa-print"></i></a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>

        

        <table class="table table-striped">
            <thead>
                <tr>
                    @{
                        int sno = 0;
                    }
                    <th>SL No.</th>
                    <th>Journel Voucher No.</th>
                    <th>Date</th>
                    <th>Reference</th>
                    <th>Dr Amount</th>
                    <th>Cr Amount</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody id="SetDepartmentList">
                <tr id="LoadingStatus" style="color:red"></tr>
                @foreach (var item in Model.journalVoucherList)
                {
                    <tr id="@item.Id">

                        <td>
                            @{ sno++; }
                            @sno
                        </td>
                        <td>@item.Id</td>
                        <td>@item.Date</td>
                        <td>@item.Reference</td>
                        <td>@item.TotalDebit</td>
                        <td>@item.TotalCredit</td>
                        <td>
                            @if (Model.userP.UpdatePermission)
                            {
                            <a href='#' class="btn btn-primary btn-xs btn-marign-8x fa fa-edit" title="Edit" onclick="location.href='@Url.Action("JournalVoucherEdit", "Financial", new { id = @item.Id })'"></a>
                            }
                            @if (Model.userP.DisplayPermission)
                            {
                            <a href='#' class="btn btn-success btn-xs btn-marign-8x fa fa-eye" title="View" onclick="location.href='@Url.Action("JournalVoucherDetails", "Financial", new { id = @item.Id })'"></a>
                            }
                            @if (Model.userP.DeletePermission)
                            {
                            <a href='#' class="btn btn-danger btn-xs btn-marign-8x fa fa-trash" title="Delete" onclick=""></a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>


    </div>
</div>

VehicleServiceManagement/Views/Financial/PaymentVoucherIndex.cshtml
@model VehicleServiceManagement.Models.Accounts.PaymentVoucherMasterDisplay

@{
    ViewData["Title"] = "PaymentVoucherIndex";
    Layout = "~/Views/Shared/_FinancialLayout.cshtml";

}
<div class="box box-primary">
    <div class="box-header with-border">
        <h2 class="box-title">Payment Voucher Informations</h2>
    </div>
    <div class="box-body">
        <div class="row mb-7">
            <div class="col-sm-12">
                <div class="pur-in-btn">
                    <ul>
                        @if (Model.userP.InsertPermission)
                        {
                        <li><a asp-action="PaymentVoucherCreate" asp-controller="Financial">New <i class="fa fa-plus"></i></a></li>
                        }
                        @*<li><a href="/Financial/PaymentVoucherEdit">Edit <i class="fa fa-edit"></i></a></li>
                        <li><a href="/Financial/PaymentVoucherDelete">Delete <i class="fa fa-trash"></i></a></li>*@
                        <li><a asp-action="index" asp-controller="Financial">Cancel <i class="fa fa-ban"></i></a></li>
                        @if (Model.userP.PrintPermission)
                        {
                        <li><a href="">Print <i class="fa fa-print"></i></a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>

        
        <table class="table table-striped">
            <thead>
                <tr>
                    @{
                        int sno = 0;
                    }
                    <th>SL No.</th>
                    <th>Payment Voucher No.</th>
                    <th>Date</th>
                    <th>Vendor / Dr Account</th>
                    <th>Reference</th>
                    <th>Paid Amount</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody id="SetDepartmentList">
                <tr id="LoadingStatus" style="color:red"></tr>
                @foreach (var item in Model.paymentVoucherList)
                {
            <tr id="@item.Id">

                <td>
                    @{ sno++; }
                    @sno
                </td>
                <td>@item.Id</td>
                <td>@item.Date</td>
                <td>@item.PaymentMethod</td>
                <td>@item.Reference</td>             
                <td>@item.PaidAmount</td>
                <td>
                    @*<a href='#' class="btn btn-primary btn-xs btn-marign-8x fa fa-edit" title="Edit" onclick="location.href='@Url.Action("PaymentVoucherEdit", "Financial",new {id=@item.Id })'"></a>*@
                    @if (Model.userP.DisplayPermission)
                    {
                    <a href='#' class="btn btn-success btn-xs btn-marign-8x fa fa-eye" title="View" onclick="location.href='@Url.Action("PaymentVoucherDetails", "Financial", new { id = @item.Id })'"></a>
                    }
                    @*<a href='#' class="btn btn-danger btn-xs btn-marign-8x fa fa-trash" title="Delete" onclick=""></a>*@
                </td>
            </tr>
                }
            </tbody>
        </table>

    </div>
</div>